apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: backend-cpu-alert
  namespace: yaml-yodelers
spec:
  groups:
  - name: backend-cpu-alerts
    rules:
    - alert: HighCpuUsage
      expr: 100 - (avg(irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 90
      for: 1m
      labels:
        severity: warning
      annotations:
        summary: "High CPU usage on backend service"
        description: "CPU usage on backend service {{ $labels.instance }} is above 90% for the last 5 minutes."
