apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: ghcr.io/antonpieper/simple-app-server:main
          env:
            - name: PGHOST
              value: simple-app-db
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  name: simple-app-user.simple-app-db.credentials.postgresql.acid.zalan.do
                  key: username
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: simple-app-user.simple-app-db.credentials.postgresql.acid.zalan.do
                  key: password
            - name: PGDATABASE
              value: simple_app
            - name: PGSSLMODE
              value: "require"
            - name: HOST
              value: "0.0.0.0"
            - name: PORT
              value: "8080"
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "0.5"
              memory: "512Mi"
            requests:
              cpu: "0.1"
              memory: "256Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
