apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: yaml-yodelers
  labels:
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/enforce-version: v1.24
  name: backend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      namespace: yaml-yodelers
      labels:
        app: backend
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - backend
              topologyKey: kubernetes.io/hostname
      containers:
        - name: backend
          image: ghcr.io/antonpieper/simple-app-server:main
          env:
            - name: PGHOST
              value: simple-app-db
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  name: simple-app-user.simple-app-db.credentials.postgresql.acid.zalan.do
                  key: username
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: simple-app-user.simple-app-db.credentials.postgresql.acid.zalan.do
                  key: password
            - name: PGDATABASE
              value: simple_app
            - name: PGSSLMODE
              value: "require"
            - name: HOST
              value: "0.0.0.0"
            - name: PORT
              value: "8080"
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "0.5"
              memory: "512Mi"
            requests:
              cpu: "0.1"
              memory: "256Mi"

---
apiVersion: v1
kind: Service
metadata:
  namespace: yaml-yodelers
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  namespace: yaml-yodelers
  name: backend-ingress-policy
spec:
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: frontend
      ports:
        - port: 8080
  podSelector:
    matchLabels:
      app: backend
  policyTypes:
    - Ingress

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  namespace: yaml-yodelers
  name: backend-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: backend
