apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: yaml-yodelers
  labels:
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/enforce-version: v1.24
  name: frontend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      namespace: yaml-yodelers
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: ghcr.io/antonpieper/simple-app-client:main
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: "0.5"
              memory: "512Mi"
            requests:
              cpu: "0.1"
              memory: "128Mi"

---
apiVersion: v1
kind: Service
metadata:
  namespace: yaml-yodelers
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  namespace: yaml-yodelers
  name: frontend-ingress-policy
spec:
  ingress:
    - from:
        - podSelector:
            matchLabels:
              role: backend
      ports:
        - port: 80
          protocol: TCP
  podSelector:
    matchLabels:
      app: frontend
  policyTypes:
    - Ingress

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: yaml-yodelers
  name: frontend-ingress
spec:
  rules:
    - host: example.com #TODO replace with proper TLD
      http:
        paths:
          - backend:
              service:
                name: frontend-service
                port:
                  number: 80
            path: /
            pathType: Prefix

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  namespace: yaml-yodelers
  name: frontend-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: frontend
