apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  namespace: yaml-yodelers
  name: simple-app-db
spec:
  teamId: "myteam"
  volume:
    size: 1Gi
  numberOfInstances: 2
  users:
    simple_app_user:
      - superuser
      - createdb
  databases:
    simple_app: simple_app_user
  postgresql:
    version: "16"
    parameters:
      password_encryption: "scram-sha-256"
  resources:
    requests:
      cpu: 10m
      memory: 100Mi
    limits:
      cpu: 300m
      memory: 300Mi
