apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: backend-service-monitor
  namespace: yaml-yodelers
spec:
  selector:
    matchLabels:
      app: backend
  endpoints:
  - port: "8080"
    path: /metrics
    interval: 30s
