apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: backend-service-monitor
  namespace: yaml-yodelers
    labels:
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/enforce-version: v1.24
spec:
  selector:
    matchLabels:
      app: backend
  endpoints:
  - port: "8080"
    path: /metrics
    interval: 30s
